Repository Nexters/CREW_Server, pull requests merged in 2019-02, with the labels that each got.

#11 create form schema
  src/db/DbInterface/index.d.ts
  src/models/form.ts
  src/models/index.ts
Labels: enhancement

#12 Feature/sj #9 resumeschema
  .env.dist
  .gitignore
  dist/api/auth/index.js
  dist/api/auth/index.js.map
  dist/app.js
  dist/app.js.map
  dist/middleware.js
  dist/middleware.js.map
  dist/models/user.js
  dist/models/user.js.map
  dist/query.js
  dist/query.js.map
  package-lock.json
  package.json
  src/api/auth/index.ts
  src/app.ts
  src/db/DbInterface/index.d.ts
  src/middleware.ts
  src/models/form.ts
  src/models/index.ts
  src/models/resume.ts
  src/models/user.ts
  tsconfig.json
  views/auth.pug
  views/success.pug
Labels: enhancement

#17 Feature/sj #14 add user col
  src/models/form.ts
  src/models/user.ts
Labels: enhancement

#24 Feature/sj change router
  dist/api/auth/index.js
  dist/api/auth/index.js.map
  dist/api/user/index.js
  dist/api/user/index.js.map
  dist/models/form.js
  dist/models/form.js.map
  dist/models/user.js
  dist/models/user.js.map
  dist/query.js
  dist/query.js.map
  src/api/auth/index.ts
  src/api/user/index.ts
  src/query.ts
Labels: enhancement

#28 Feature/sj #20 get resumes
  dist/api/resume/index.js
  dist/api/resume/index.js.map
  dist/app.js
  dist/app.js.map
  dist/middleware.js
  dist/middleware.js.map
  dist/query.js
  dist/query.js.map
  package-lock.json
  package.json
  src/api/resume/index.ts
  src/app.ts
  src/middleware.ts
  src/query.ts
Labels: enhancement

#33 get resumes/read api 개발
  dist/api/resume/index.js
  dist/api/resume/index.js.map
  dist/query.js
  dist/query.js.map
  src/api/resume/index.ts
  src/query.ts
Labels: enhancement

#38 [get] evaluaiton
  dist/models/user.js
  dist/models/user.js.map
  dist/query.js
  dist/query.js.map
  src/api/evaluation/index.ts
  src/query.ts
Labels: enhancement

#41 ApplicationResultObject commit for approval
  src/api/evaluation/index.ts
  src/api/resume/index.ts
  src/app.ts
  src/query.ts
  src/util/index.ts
Labels: enhancement

#47 add bracket to util/index
  src/util/index.ts
Labels: bug

#49 fix error which is caused by applying of AppResult module
  src/api/user/index.ts
Labels: bug

#51 Feature/sj #22 post resumes
  .env.dist
  package-lock.json
  package.json
  src/api/resume/index.ts
  src/models/form.ts
  src/query.ts
Labels: enhancement

#42 Feature/hg #23 mail
  package-lock.json
  package.json
  src/api/mail/index.ts
  src/app.ts
Labels: enhancement

#54 add .env.dist for node mailer
  .env.dist
Labels: enhancement

#55 Feature/4whomtbts form methods
  .env.dist
  README.md
  package-lock.json
  src/api/evaluation/README.md
  src/api/evaluation/index.ts
  src/api/form/README.md
  src/api/form/index.ts
  src/api/resume/index.ts
  src/api/user/README.md
  src/app.ts
  src/models/form.ts
  src/query.ts
  src/util/index.ts
Labels: Refactoring, bug, enhancement

#57 Develop
  .env.dist
  .gitignore
  README.md
  dist/api/auth/index.js
  dist/api/auth/index.js.map
  dist/api/evaluation/index.js
  dist/api/evaluation/index.js.map
  dist/api/form/index.js
  dist/api/form/index.js.map
  dist/api/mail/index.js
  dist/api/mail/index.js.map
  dist/api/resume/index.js
  dist/api/resume/index.js.map
  dist/api/user/index.js
  dist/api/user/index.js.map
  dist/app.js
  dist/app.js.map
  dist/config/awsconfig.js
  dist/config/awsconfig.js.map
  dist/config/config.js
  dist/config/config.js.map
  dist/middleware.js
  dist/middleware.js.map
  dist/models/evaluation.js
  dist/models/evaluation.js.map
  dist/models/form.js
  dist/models/form.js.map
  dist/models/index.js
  dist/models/index.js.map
  dist/models/resume.js
  dist/models/resume.js.map
  dist/models/user.js
  dist/models/user.js.map
  dist/query.js
  dist/query.js.map
  dist/util/index.js
  dist/util/index.js.map
  package-lock.json
  package.json
  src/api/auth/index.ts
  src/api/evaluation/index.ts
  src/api/form/index.ts
  src/api/mail/index.ts
  src/api/resume/index.ts
  src/api/user/index.ts
  src/app.ts
  src/config/config.ts
  src/db/DbInterface/index.d.ts
  src/middleware.ts
  src/models/evaluation.ts
  src/models/form.ts
  src/models/index.ts
  src/models/resume.ts
  src/models/user.ts
  src/query.ts
  src/util/index.ts
Labels: enhancement

#59 Feature/#58 sj swagger
  dist/api/mail/index.js
  dist/api/mail/index.js.map
  dist/api/resume/index.js
  dist/api/resume/index.js.map
  dist/api/user/index.js
  dist/api/user/index.js.map
  dist/app.js
  dist/app.js.map
  dist/swagger.js
  dist/swagger.js.map
  package-lock.json
  package.json
  src/api/evaluation/index.ts
  src/api/form/index.ts
  src/api/mail/index.ts
  src/api/resume/index.ts
  src/api/user/index.ts
  src/app.ts
  src/swagger.ts
Labels: enhancement
